### ISSUE TITLE
Change the color of the black background.

### ISSUE THREAD

**Issue by sylveon** [Bungalow12/AnimatedImage#2]
I've made a nice viewer based on yours. In Windows 7, it gives a pretty cool result:  
![capture](https://cloud.githubusercontent.com/assets/6440374/9980606/d6e904d2-5f6d-11e5-91ef-c5325354e54b.PNG)
But in Windows 10, it's another thing:
![capture2](https://cloud.githubusercontent.com/assets/6440374/9980612/fbb921ac-5f6d-11e5-9eba-fafda6cc8010.PNG)

Is there any way to change the background to white instead of dark? I've tried all possible things for transparency in Windows Forms I've found on Internet.

**Comment by ghost** [comment]
That's pretty awesome Charles! Perhaps you'd be willing to be added as a contributor. 
Of course if the background code is not platform agnostic it would need to be wrapped. This app may not work perfectly on UNIX or OSX right now but as .Net core gets more open source support Mono will likely be a shim for .Net core and all this may work.

As for the black background I can't say for sure about the black background on windows 10 but my bet is that your transparency code is working however there is nothing behind it. 
I'm wondering if Windows 10 is running all apps in an app container similar to the universal apps. If so that may be why it does not get the visuals from behind the application as there is simply nothing there. I haven't tried this on Windows 10 yet anyway but I can check. 
This may be a candidate to detect if you are running Windows 10 and force a white non-transparent background.

**Comment by Bungalow12** [comment]
Bah the previous was me too. Sadly I forget I have a work and personal git name. Poor decision on my part. :/

**Comment by sylveon** [comment]
Adding something behind when I use transparency still gives black... BackColor also.
I already have Windows 10 specific code, cause else, it looks really more ugly than this in Windows 10.

I'd like to see what it looks like in Windows 8, you can download it [here](http://www.mediafire.com/download/se77dmrzmv5nair/Animated+Image+Viewer.exe)

I do not plan compatibility for other OSes cause : 
1. I do not have thoses at disposition
2. It was made for personnal use

**Comment by sylveon** [comment]
Also, when finished, if you want, I can release it's source code under a fork.

**Comment by Bungalow12** [comment]
That'd be great.
On Sep 20, 2015 11:33 AM, Charles Milette notifications@github.com wrote:Also, when finished, if you want, I can release it's source code under a fork.

**Comment by Bungalow12** [comment]
I'll look over the drawing code I'm doing in Windows 10 and see if there is something causing trouble there.
On Sep 20, 2015 11:27 AM, Charles Milette notifications@github.com wrote:Adding something behind when I use transparency still gives black... BackColor also.
I already have Windows 10 specific code, cause else, it looks really more ugly than this in Windows 10.

I'd like to see what it looks like in Windows 8, you can download it here

**Comment by sylveon** [comment]
Note: The Win 10 specific code only affects the app not the library.  
Probably that by adding something in the library that detects Windows 10 and colors the background in white before sending it to the Windows Form will work.

**Comment by Bungalow12** [comment]
That's what I was thinknig. I'll look into it.

-------- Original Message --------
Subject: Re: [AnimatedImage] Change the color of the black background.
(#2)

**Comment by Bungalow12** [comment]
![capture](https://cloud.githubusercontent.com/assets/2235941/9983565/99450f8e-5fb5-11e5-88f8-44039b08507f.PNG)
This is what it looks like on Windows 8.1 with your version of the app.

-------- Original Message --------
Subject: Re: [AnimatedImage] Change the color of the black background.
(#2)

**Comment by sylveon** [comment]
Thanks for the capture!  
I'll save you from something: `GetVersionEx` is deprecated and will return 6.2 (Windows 8) on Windows 10 at runtime.
Use this instead:  

``` c#
private static bool IsWindows10()
{
    var reg = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows NT\CurrentVersion");
    string productName = (string)reg.GetValue("ProductName");
    return productName.StartsWith("Windows 10");
}
```

Usage:

``` c#
if (IsWindows10())
{
    // Windows 10 only stuff
}
```

**Comment by sylveon** [comment]
I've tried something... It works, but triggers the following exception:
![capture](https://cloud.githubusercontent.com/assets/6440374/9983644/f4d3509c-5fd1-11e5-9d1b-4288a5da2eeb.PNG)
Basically, I've replace the HandleTick by this

``` c#
        /// <summary>
        /// Updates the frame.
        /// </summary>
        /// <param name="sender">Sender.</param>
        /// <param name="e">Event args.</param>
        protected void HandleTick(object sender, EventArgs e)
        {
            if (image != null)
            {
                if (currentFrame >= image.FrameCount)
                {
                    Drawn = null;
                    if (image.PlayCount > 0)
                    {
                        if (++curPlayCount > image.PlayCount)
                        {
                            curImage = image.GetDefaultImage();
                            animationTimer.Stop();
                            return;
                        }
                    }
                    currentFrame = 0;
                }

                Bitmap frame = image[currentFrame++];
                if (Viewer.AnimatedImageViewer.IsWindows10())
                {
                    Graphics g = Graphics.FromImage(frame);
                    g.Clear(Color.White);
                    g.DrawImage(image[currentFrame++], 0, 0);
                }
                curImage = frame;

                animationTimer.Interval = (image.GetFrameRate(currentFrame) != 0) ? image.GetFrameRate(currentFrame) : image.FrameRate;

                Invalidate();
            }
        }
```

What's wrong?

**Comment by sylveon** [comment]
The problem fixed itslef by compiling and running in Windows 10 under Vs 2015... i'll be creating a fork soon.

**Comment by Bungalow12** [comment]
Great news Charles! Thanks!
On Sep 23, 2015 4:13 PM, Charles Milette notifications@github.com wrote:The problem fixed itslef by compiling and running in Windows 10 under Vs 2015... i'll be creating a fork soon.

**Comment by sylveon** [comment]
Done: https://github.com/charlesmilette/APNGViewer
